# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.
# fibonacci = [1,2]
# sum = 0
# sum1 = 0
# for i in range (2,33):
#     if fibonacci[i-1] + fibonacci[i-2] < 4000000:
#         sayi = fibonacci[i-1] + fibonacci[i-2]
#         fibonacci.append(sayi)
#         if fibonacci[i-2] % 2 == 0:
#             sum += fibonacci[i-2]
#     else:
#         break
            #print(fibonacci[i-2])
#print(fibonacci)
print(sum)
print(sum1)

#başka çözüm
fibo = list()
fibo.append(1)
fibo.append(2)

i = 2
while True:
    if fibo[i-1] + fibo[i-2] < 4000000:
        fibo.append(fibo[i-1] + fibo[i-2])
        i += 1
    else:
        break

summ = 0
for i in fibo:
    if i % 2 == 0:
        summ += i
print(summ)